# Generated by Django 5.2.6 on 2025-09-20 18:21

import django.core.validators
import django.db.models.deletion
import naya_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=naya_site.models.upload_image, verbose_name='Product Image')),
                ('minimum_quantity', models.IntegerField(default=5, help_text='Quantidade abaixo de minimo necessário em estoque', verbose_name='Minimum Quantity')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naya_site.category')),
            ],
        ),
    ]
