# Generated by Django 5.2.6 on 2025-09-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
