# Generated by Django 5.2.6 on 2025-09-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Sem categoria', max_length=50),
        ),
    ]
