# Generated by Django 5.2.6 on 2025-09-22 17:51

import naya_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0003_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=naya_site.models.upload_image),
        ),
    ]
