# Generated by Django 5.2.6 on 2025-10-08 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0008_alter_state_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('descricao_personalizacao', models.TextField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naya_site.product')),
            ],
            options={
                'verbose_name': 'Item do Orçamento',
                'verbose_name_plural': 'Itens do Orçamento',
            },
        ),
        migrations.CreateModel(
            name='ArquivoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='orcamentos/arquivos/')),
                ('tipo', models.CharField(choices=[('cliente', 'Arquivo do Cliente'), ('empresa', 'Arquivo da Empresa')], max_length=10)),
                ('nome_original', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('item_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='naya_site.itemorcamento')),
            ],
            options={
                'verbose_name': 'Arquivo do Orçamento',
                'verbose_name_plural': 'Arquivos do Orçamento',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_maxima_entrega', models.DateField()),
                ('status', models.CharField(choices=[('sem_orcamento', 'Sem Orçamentos'), ('aguardando_resposta', 'Aguardando Resposta'), ('aguardando_cliente', 'Aguardando Resposta'), ('aprovado', 'Orçamento Aprovado'), ('em_producao', 'Em Produção'), ('rejeitado', 'Rejeitado'), ('finalizado', 'Finalizado')], default='aguardando_resposta', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_prevista_entrega', models.DateField(blank=True, null=True)),
                ('observacoes_empresa', models.TextField(blank=True)),
                ('observacoes_cliente', models.TextField(blank=True)),
                ('nao_possivel_prazo', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='naya_site.orcamento'),
        ),
    ]
