# Generated by Django 5.2.6 on 2025-10-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0011_alter_userprofile_cep_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_conclusao_producao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da Produção'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_inicio_producao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Produção'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes_producao',
            field=models.TextField(blank=True, verbose_name='Observações da Produção'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='ordem_servico_criada',
            field=models.BooleanField(default=False, verbose_name='OS Criada'),
        ),
    ]
