# Generated by Django 5.2.6 on 2025-10-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0012_orcamento_data_conclusao_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='numero_os',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número da OS'),
        ),
    ]
