# Generated by Django 5.2.6 on 2025-11-04 22:04
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0014_categoriagaleria_imagemgaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemgaleria',
            name='data_upload',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
