# Generated by Django 5.2.6 on 2025-11-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0015_imagemgaleria_data_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemgaleria',
            name='data_upload',
        ),
    ]
