# Generated by Django 5.2.6 on 2025-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0017_imagemgaleria_data_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemgaleria',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
