# Generated by Django 5.2.6 on 2025-11-05 00:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0018_alter_imagemgaleria_data_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriagaleria',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria da Galeria', 'verbose_name_plural': 'Categorias da Galeria'},
        ),
        migrations.AlterModelOptions(
            name='imagemgaleria',
            options={'ordering': ['ordem', '-data_upload'], 'verbose_name': 'Imagem da Galeria', 'verbose_name_plural': 'Imagens da Galeria'},
        ),
        migrations.AddField(
            model_name='categoriagaleria',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriagaleria',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagemgaleria',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagemgaleria',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagemgaleria',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
