# Generated by Django 5.2.6 on 2025-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naya_site', '0019_alter_categoriagaleria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoorcamento',
            name='aprovado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivoorcamento',
            name='observacoes_alteracao',
            field=models.TextField(blank=True),
        ),
    ]
